### ISSUE TITLE
Add toml parser and basic external target parsing

### ISSUE THREAD

**Issue by GPMueller** [GPMueller/clang-build-test#4]
Should be able to parse a basic example such as
```TOML
[myexe]
[myexe.sources]
include_directories = ["myexe/include"]
source_directories = ["myexe/src"]
[myexe.link]
dependencies = ["eigen"]
flags = ["-DEIGEN_NO_FAST_MATH"]

[eigen]
external = true
url = "https://github.com/eigenteam/eigen-git-mirror"
```
